# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  ruby: circleci/ruby@1.2.0
  node: circleci/node@4.9.0

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build:
    docker:
      - image: cimg/ruby:3.2.0-node
    executor: ruby/default
    steps:
      - checkout
      - ruby/install-deps
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Which bundler?
          command: bundle -v
  linter:
    docker:
      - image: cimg/ruby:3.2.0
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rubocop-check:
          format: progress
          label: Inspecting with Rubocop
          check-path: app

  test:
    docker:
      - image: cimg/ruby:3.2.0-node
      - image: cimg/postgres:15.1
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: ogpreview_test
          POSTGRES_PASSWORD: postgres
    environment:
      BUNDLE_JOBS: '4'
      BUNDLE_RETRY: '3'
      DB_HOST: 127.0.0.1
      RAILS_ENV: test

    steps:
      - checkout
      - ruby/install-deps
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Webpacker
          command: bundle exec rails webpacker:compile
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Database setup
          command: bundle exec rails db:schema:load --trace
      - ruby/rspec-test

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  build_and_test:
    jobs:
      - build
      - linter
      - test:
          requires:
            - build
            - linter
